xrp:
  env: ${INPUT_XRP_ENV:TESTNET}
  name: XRPL
  wallet_seed: ${INPUT_XRP_WALLET_SEED}
  amount: ${INPUT_XRP_AMOUNT:10000000}
  server: ${INPUT_XRP_SERVER:test.xrp.xpring.io:50051}
ether:
  name: ETH
  env: ${INPUT_ETH_ENV:TESTNET}
  wallet_seed: ${INPUT_ETH_WALLET_SEED}
  amount: 0.01
  server: ${INPUT_ETH_SERVER:https://ropsten.infura.io/v3/ed181538cfd34f6a86248de8890d82c4}
bitcoin:
  name: BTC
  env:
  wallet_seed: mmEva6Kq5feCSgqs6Xv3GAkJzymjS7azKV
  amount: 0.000001
  server:

github_token: ${INPUT_GITHUB_TOKEN}
github_event: ${INPUT_GITHUB_EVENT}
