xrp:
  env: ${INPUT_XRP_ENV:TESTNET}
  name: XRPL
  wallet_seed: ${INPUT_XRP_WALLET_SEED:seed_not_sent_via_env_variable}
  amount: ${INPUT_XRP_AMOUNT:10000000}
  server: ${INPUT_XRP_SERVER:test.xrp.xpring.io:50051}
ether:
  name: ETH
  env: ROPSTEN
  wallet_seed: 0x9c24D77E8A24dE30be9a3e6267f110C602d8EAd7
  amount: 0.0001
  server:
bitcoin:
  name: BTC
  env:
  wallet_seed: mmEva6Kq5feCSgqs6Xv3GAkJzymjS7azKV
  amount: 0.000001
  server:

github_event: ${INPUT_GITHUB_EVENT:event_not_sent_via_env_variable}

#github_event: '{
#                  "token":"***",
#                  "job":"build",
#                  "ref":"refs/heads/master",
#                  "sha":"c77c89f0138aba55d6c3aed4adc17975f988f28d",
#                  "repository":"deepakvalluru/gitpay",
#                  "repository_owner":"deepakvalluru",
#                  "repositoryUrl":"git://github.com/deepakvalluru/gitpay.git",
#                  "run_id":"409835049",
#                  "run_number":"9",
#                  "retention_days":"90",
#                  "actor":"deepakvalluru",
#                  "workflow":"gitpay",
#                  "head_ref":"",
#                  "base_ref":"",
#                  "event_name":"push",
#                  "event":{
#                     "after":"c77c89f0138aba55d6c3aed4adc17975f988f28d",
#                     "base_ref":null,
#                     "before":"db6e4ca1e283e9caa298013ed55315fc42b3ce39",
#                     "commits":[
#                        {
#                           "author":{
#                              "email":"deepak.valluru@aa.com",
#                              "name":"Deepak"
#                           },
#                           "committer":{
#                              "email":"deepak.valluru@aa.com",
#                              "name":"Deepak"
#                           },
#                           "distinct":false,
#                           "id":"ac2471ed4425fc0f5be6a8ba0bd3305716523442",
#                           "message":"udpate github action with pay id - deepakvalluru$ripplex.money",
#                           "timestamp":"2020-12-08T22:45:33-06:00",
#                           "tree_id":"c055cd0dce327a79323dc2baa41c3774e0f0f163",
#                           "url":"https://github.com/deepakvalluru/gitpay/commit/ac2471ed4425fc0f5be6a8ba0bd3305716523442"
#                        },
#                        {
#                           "author":{
#                              "email":"deepak.valluru@aa.com",
#                              "name":"Deepak"
#                           },
#                           "committer":{
#                              "email":"deepak.valluru@aa.com",
#                              "name":"Deepak"
#                           },
#                           "distinct":false,
#                           "id":"2d6155347793027161ec03ba97c10a1be3b6f90a",
#                           "message":"udpate github action also with another pay id - deepakvalluru$ripplex.money",
#                           "timestamp":"2020-12-08T22:45:53-06:00",
#                           "tree_id":"c524cb2cc6deff335bf0c15fd1ced46d67db105b",
#                           "url":"https://github.com/deepakvalluru/gitpay/commit/2d6155347793027161ec03ba97c10a1be3b6f90a"
#                        },
#                        {
#                           "author":{
#                              "email":"deepakvalluru@gmail.com",
#                              "name":"deepakvalluru",
#                              "username":"deepakvalluru"
#                           },
#                           "committer":{
#                              "email":"noreply@github.com",
#                              "name":"GitHub",
#                              "username":"web-flow"
#                           },
#                           "distinct":true,
#                           "id":"c77c89f0138aba55d6c3aed4adc17975f988f28d",
#                           "message":"Merge pull request #4 from deepakvalluru/deepak\n\nPR Title",
#                           "timestamp":"2020-12-08T22:50:29-06:00",
#                           "tree_id":"c524cb2cc6deff335bf0c15fd1ced46d67db105b",
#                           "url":"https://github.com/deepakvalluru/gitpay/commit/c77c89f0138aba55d6c3aed4adc17975f988f28d"
#                        }
#                     ],
#                     "compare":"https://github.com/deepakvalluru/gitpay/compare/db6e4ca1e283...c77c89f0138a",
#                     "created":false,
#                     "deleted":false,
#                     "forced":false,
#                     "head_commit":{
#                        "author":{
#                           "email":"deepakvalluru@gmail.com",
#                           "name":"deepakvalluru",
#                           "username":"deepakvalluru"
#                        },
#                        "committer":{
#                           "email":"noreply@github.com",
#                           "name":"GitHub",
#                           "username":"web-flow"
#                        },
#                        "distinct":true,
#                        "id":"c77c89f0138aba55d6c3aed4adc17975f988f28d",
#                        "message":"Merge pull request #4 from deepakvalluru/deepak\n\nPR Title",
#                        "timestamp":"2020-12-08T22:50:29-06:00",
#                        "tree_id":"c524cb2cc6deff335bf0c15fd1ced46d67db105b",
#                        "url":"https://github.com/deepakvalluru/gitpay/commit/c77c89f0138aba55d6c3aed4adc17975f988f28d"
#                     },
#                     "pusher":{
#                        "email":"deepakvalluru@gmail.com",
#                        "name":"deepakvalluru"
#                     },
#                     "ref":"refs/heads/master",
#                     "repository":{
#                        "archive_url":"https://api.github.com/repos/deepakvalluru/gitpay/{archive_format}{/ref}",
#                        "archived":false,
#                        "assignees_url":"https://api.github.com/repos/deepakvalluru/gitpay/assignees{/user}",
#                        "blobs_url":"https://api.github.com/repos/deepakvalluru/gitpay/git/blobs{/sha}",
#                        "branches_url":"https://api.github.com/repos/deepakvalluru/gitpay/branches{/branch}",
#                        "clone_url":"https://github.com/deepakvalluru/gitpay.git",
#                        "collaborators_url":"https://api.github.com/repos/deepakvalluru/gitpay/collaborators{/collaborator}",
#                        "comments_url":"https://api.github.com/repos/deepakvalluru/gitpay/comments{/number}",
#                        "commits_url":"https://api.github.com/repos/deepakvalluru/gitpay/commits{/sha}",
#                        "compare_url":"https://api.github.com/repos/deepakvalluru/gitpay/compare/{base}...{head}",
#                        "contents_url":"https://api.github.com/repos/deepakvalluru/gitpay/contents/{+path}",
#                        "contributors_url":"https://api.github.com/repos/deepakvalluru/gitpay/contributors",
#                        "created_at":1607215467,
#                        "default_branch":"master",
#                        "deployments_url":"https://api.github.com/repos/deepakvalluru/gitpay/deployments",
#                        "description":null,
#                        "disabled":false,
#                        "downloads_url":"https://api.github.com/repos/deepakvalluru/gitpay/downloads",
#                        "events_url":"https://api.github.com/repos/deepakvalluru/gitpay/events",
#                        "fork":false,
#                        "forks":0,
#                        "forks_count":0,
#                        "forks_url":"https://api.github.com/repos/deepakvalluru/gitpay/forks",
#                        "full_name":"deepakvalluru/gitpay",
#                        "git_commits_url":"https://api.github.com/repos/deepakvalluru/gitpay/git/commits{/sha}",
#                        "git_refs_url":"https://api.github.com/repos/deepakvalluru/gitpay/git/refs{/sha}",
#                        "git_tags_url":"https://api.github.com/repos/deepakvalluru/gitpay/git/tags{/sha}",
#                        "git_url":"git://github.com/deepakvalluru/gitpay.git",
#                        "has_downloads":true,
#                        "has_issues":true,
#                        "has_pages":false,
#                        "has_projects":true,
#                        "has_wiki":true,
#                        "homepage":null,
#                        "hooks_url":"https://api.github.com/repos/deepakvalluru/gitpay/hooks",
#                        "html_url":"https://github.com/deepakvalluru/gitpay",
#                        "id":318920232,
#                        "issue_comment_url":"https://api.github.com/repos/deepakvalluru/gitpay/issues/comments{/number}",
#                        "issue_events_url":"https://api.github.com/repos/deepakvalluru/gitpay/issues/events{/number}",
#                        "issues_url":"https://api.github.com/repos/deepakvalluru/gitpay/issues{/number}",
#                        "keys_url":"https://api.github.com/repos/deepakvalluru/gitpay/keys{/key_id}",
#                        "labels_url":"https://api.github.com/repos/deepakvalluru/gitpay/labels{/name}",
#                        "language":"Java",
#                        "languages_url":"https://api.github.com/repos/deepakvalluru/gitpay/languages",
#                        "license":null,
#                        "master_branch":"master",
#                        "merges_url":"https://api.github.com/repos/deepakvalluru/gitpay/merges",
#                        "milestones_url":"https://api.github.com/repos/deepakvalluru/gitpay/milestones{/number}",
#                        "mirror_url":null,
#                        "name":"gitpay",
#                        "node_id":"MDEwOlJlcG9zaXRvcnkzMTg5MjAyMzI=",
#                        "notifications_url":"https://api.github.com/repos/deepakvalluru/gitpay/notifications{?since,all,participating}",
#                        "open_issues":0,
#                        "open_issues_count":0,
#                        "owner":{
#                           "avatar_url":"https://avatars0.githubusercontent.com/u/26495060?v=4",
#                           "email":"deepakvalluru@gmail.com",
#                           "events_url":"https://api.github.com/users/deepakvalluru/events{/privacy}",
#                           "followers_url":"https://api.github.com/users/deepakvalluru/followers",
#                           "following_url":"https://api.github.com/users/deepakvalluru/following{/other_user}",
#                           "gists_url":"https://api.github.com/users/deepakvalluru/gists{/gist_id}",
#                           "gravatar_id":"",
#                           "html_url":"https://github.com/deepakvalluru",
#                           "id":26495060,
#                           "login":"deepakvalluru",
#                           "name":"deepakvalluru",
#                           "node_id":"MDQ6VXNlcjI2NDk1MDYw",
#                           "organizations_url":"https://api.github.com/users/deepakvalluru/orgs",
#                           "received_events_url":"https://api.github.com/users/deepakvalluru/received_events",
#                           "repos_url":"https://api.github.com/users/deepakvalluru/repos",
#                           "site_admin":false,
#                           "starred_url":"https://api.github.com/users/deepakvalluru/starred{/owner}{/repo}",
#                           "subscriptions_url":"https://api.github.com/users/deepakvalluru/subscriptions",
#                           "type":"User",
#                           "url":"https://api.github.com/users/deepakvalluru"
#                        },
#                        "private":false,
#                        "pulls_url":"https://api.github.com/repos/deepakvalluru/gitpay/pulls{/number}",
#                        "pushed_at":1607489430,
#                        "releases_url":"https://api.github.com/repos/deepakvalluru/gitpay/releases{/id}",
#                        "size":69,
#                        "ssh_url":"git@github.com:deepakvalluru/gitpay.git",
#                        "stargazers":0,
#                        "stargazers_count":0,
#                        "stargazers_url":"https://api.github.com/repos/deepakvalluru/gitpay/stargazers",
#                        "statuses_url":"https://api.github.com/repos/deepakvalluru/gitpay/statuses/{sha}",
#                        "subscribers_url":"https://api.github.com/repos/deepakvalluru/gitpay/subscribers",
#                        "subscription_url":"https://api.github.com/repos/deepakvalluru/gitpay/subscription",
#                        "svn_url":"https://github.com/deepakvalluru/gitpay",
#                        "tags_url":"https://api.github.com/repos/deepakvalluru/gitpay/tags",
#                        "teams_url":"https://api.github.com/repos/deepakvalluru/gitpay/teams",
#                        "trees_url":"https://api.github.com/repos/deepakvalluru/gitpay/git/trees{/sha}",
#                        "updated_at":"2020-12-09T04:44:51Z",
#                        "url":"https://github.com/deepakvalluru/gitpay",
#                        "watchers":0,
#                        "watchers_count":0
#                     },
#                     "sender":{
#                        "avatar_url":"https://avatars0.githubusercontent.com/u/26495060?v=4",
#                        "events_url":"https://api.github.com/users/deepakvalluru/events{/privacy}",
#                        "followers_url":"https://api.github.com/users/deepakvalluru/followers",
#                        "following_url":"https://api.github.com/users/deepakvalluru/following{/other_user}",
#                        "gists_url":"https://api.github.com/users/deepakvalluru/gists{/gist_id}",
#                        "gravatar_id":"",
#                        "html_url":"https://github.com/deepakvalluru",
#                        "id":26495060,
#                        "login":"deepakvalluru",
#                        "node_id":"MDQ6VXNlcjI2NDk1MDYw",
#                        "organizations_url":"https://api.github.com/users/deepakvalluru/orgs",
#                        "received_events_url":"https://api.github.com/users/deepakvalluru/received_events",
#                        "repos_url":"https://api.github.com/users/deepakvalluru/repos",
#                        "site_admin":false,
#                        "starred_url":"https://api.github.com/users/deepakvalluru/starred{/owner}{/repo}",
#                        "subscriptions_url":"https://api.github.com/users/deepakvalluru/subscriptions",
#                        "type":"User",
#                        "url":"https://api.github.com/users/deepakvalluru"
#                     }
#                  },
#                  "server_url":"https://github.com",
#                  "api_url":"https://api.github.com",
#                  "graphql_url":"https://api.github.com/graphql",
#                  "workspace":"/home/runner/work/gitpay/gitpay",
#                  "action":"deepakvallurugitpay",
#                  "event_path":"/home/runner/work/_temp/_github_workflow/event.json",
#                  "action_repository":"deepakvalluru/gitpay",
#                  "action_ref":"master",
#                  "path":"/home/runner/work/_temp/_runner_file_commands/add_path_dac3d7f3-2a6a-4f24-a818-b5deda04cc86",
#                  "env":"/home/runner/work/_temp/_runner_file_commands/set_env_dac3d7f3-2a6a-4f24-a818-b5deda04cc86"
#               }'
