# This is a basic workflow to help you get started with Actions

name: gitpay

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
   pull_request:
     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run gitpay
        uses: deepakvalluru/gitpay@master
        with:
          xrp_wallet_seed: ${{ secrets.XRP_WALLET_SEED }}
          xrp_amount: 1000000
          github_event: ${{ toJson(github) }}
